#!/bin/bash

arg=$1

export CXXFLAGS="${CXXFLAGS} -fopenmp"

case $arg in
    config)
    ;;
    build)
        make || exit 1
    ;;
    clean)
        make clean || exit 1
    ;;
    binary)
        echo "freqmine"
    ;;
esac
