#!/bin/bash

arg=$1

export version=pthreads
export CXXFLAGS="${CXXFLAGS} -fexceptions -fno-strict-aliasing -fno-align-labels -DNDEBUG -D_MM_NO_ALIGN_CHECK"

case $arg in
    config)
		rm -rf CMakeCache.txt
		cmake . || exit 1
    ;;
    build)
        make || exit 1
    ;;
    clean)
        make clean || exit 1
    ;;
    binary)
        echo "bin/rtview"
    ;;
esac
