#!/bin/bash

arg=$1

export CFLAGS="${CFLAGS} -DOPENSSL_NO_INLINE_ASM"
export version=pthreads

case $arg in
    config)
    ;;
    build)
        make || exit 1
    ;;
    clean)
        make clean || exit 1
    ;;
    binary)
        echo "dedup"
    ;;
esac
