#!/bin/bash

arg=$1

export CFLAGS="${CFLAGS} -Wno-return-type"
export CXXFLAGS="${CXXFLAGS} -Wno-return-type"

case $arg in
    config)
    ;;
    build)
        make || exit 1
    ;;
    clean)
        make clean || exit 1
    ;;
    binary)
        echo "volrend"
    ;;
esac
